### ISSUE TITLE
add withdraw to limitedlives

### ISSUE THREAD

**Issue by Jinxodabest** [srnyx/limited-lives#12]
### What and How?

i want to withdraw lives to trade/sell

### Why?

i did above these mean same thing to me

### Are there alternatives?

add withdrawing alternitave enough

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

pls add withdraw

**Comment by srnyx** [comment]
Snapshot build: https://github.com/srnyx/limited-lives/actions/runs/7152715008

**Comment by srnyx** [comment]
https://github.com/srnyx/limited-lives/commit/0224c89ff51cc0a7c33556a8ceda5ca7bc56a3b9
