### ISSUE TITLE
Data unavailable while player offline

### ISSUE THREAD

**Issue by TrueGame776** [srnyx/limited-lives#13]
### Expected behavior

Say there are two players; player X and player Y. Player Y has ran out of all their lives. Player X should be able to revive player Y by doing /lives give 1 player_Y. However, this is not possible.

### Actual behavior

Say there are two players; player X and player Y. Player Y has ran out of all their lives, and so the config.yml's final life death/respawn command is changed to "minecraft:ban %player% You ran out of lives!" (%player% is the player who lost all their lives). However, how can this person be revived now? Sure, they have been banned off the server, but there is no item that can revive them. /lives give <lives> <deadplayer> should be fixed and be able to work, while being able to configure the amount of lives the person will spawn back with.

### Steps to reproduce

Yes. If I ban the player instead of putting them into spectator, it can be easily reproduced.

### Version

Latest (https://github.com/srnyx/limited-lives/actions/runs/7229346222 I'm pretty sire

### Checks

- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

A craftable (custom recipe that can be configured) item that opens a GUI of players who are banned by losing their lives that can revive a configurable amount of players.

**Comment by srnyx** [comment]
Just realized it still won't revive players if you give them lives while they are offline
Create a new suggestion if you still want this please
