### ISSUE TITLE
PVP death cause

### ISSUE THREAD

**Issue by TrueGame776** [srnyx/limited-lives#14]
### What and How?

There is no such property that defines a player killing another player. Only [ENTITY_ATTACK] and [ENTITY_SWEEP_ATTACK] come close, both with problems. ENTITY_ATTACK can include any entity killing another one, like a zombie or a player killing another player. Sweep attack depends if the final hit on the player was a sweep hit, which considering most people do crits to do most damage, is not common. A property should be created that only defines a player killing another player.

### Why?

I am the owner of an SMP, where PvP is very common. Stealing lives becomes a huge problem, as players also lose lives to some mobs 'slaying' them, like zombies, but not creepers exploding or skeletons shooting.

### Are there alternatives?

Nope, other than ENTITY_ATTACK, which is not the best.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

A craftable (custom recipe that can be configured) item that opens a GUI of players who are banned by losing their lives that can revive a configurable amount of players.

**Comment by srnyx** [comment]
I just remembered there is `obtaining.stealing` config option. This will prevent players from gaining lives when they kill other players, however, those who die will still lose lives.
