### ISSUE TITLE
I cant consume the life

### ISSUE THREAD

**Issue by sayvin-si** [srnyx/limited-lives#17]
### Expected behavior

To be able to eat and gain a life.

### Actual behavior

It wont let me eat the life in survival mode but works in creative.

### Steps to reproduce

Craft life then eat it.

### Version

3.0.1

### Checks

- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by srnyx** [comment]
Did you have full hunger? If so, then you can't "eat" the life, you need to be at least half a bar hungry in order to eat any food item in survival

**Comment by sayvin-si** [comment]
> Did you have full hunger? If so, then you can't "eat" the life, you need to be at least half a bar hungry in order to eat any food item in survival

Yes that was it mb. Thanks.
