### ISSUE TITLE
transferring a player to another dimension

### ISSUE THREAD

**Issue by Dizover** [srnyx/limited-lives#2]
### What and How?

In the config file, user can write the name of the dimension that the player enters after losing all lives, and also in the config user can configure which gamemod the player willchange to.
lives:
   The amount of lives a player starts with
  default: 5
   The maximum amount of lives a player can have
  max: 10
   The amount of lives that puts the player into spectator
  min: 0
  after_death:
   in which dimension player will go after losing all lives
   dimension: "some_name:dimension_name"
   in what gamemode player will change after losing all lives
   gamemode: "ADVENTURE"
  

### Why?

Players need to be given a chance to regain their lives, if you implement what I wrote, server administrators will be able to make a map that players must pass in order to regain their lives and return to overworld (this is can be implemented by other plugins)

### Are there alternatives?

I think you can implement it

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

server administrators, if they want, will add the necessary dimension themselves through the datapack, as I did 
[world_limbo_dp.zip](https://github.com/srnyx/limited-lives/files/11331066/world_limbo_dp.zip)

**Comment by Dizover** [comment]
oh! that's cool! But probably you need to make sure that these commands are played only after the player is revived, or if this is not possible, then with a delay of 2 ticks, so that the commands work with /gamerule doImmediateRespawn true

**Comment by Dizover** [comment]
the power of artificial intelligence is not so great, the plugin compiles, but for some reason the execute command functions do not work [limitedlives_LimConf_PlayList.zip](https://github.com/srnyx/limited-lives/files/11335533/limitedlives_LimConf_PlayList.zip)
[limited-lives-master2.zip](https://github.com/srnyx/limited-lives/files/11335545/limited-lives-master2.zip)

**Comment by srnyx** [comment]
> But probably you need to make sure that these commands are played only after the player is resoawn

Forgot about that, I now made it so that it will wait until they respawn, and if they leave instead of respawning, it will wait for them to rejoin (will break if the server restarts if the player is considered "dead" [in death screen or left the server instead of respawning], let me know if this causes issues and I'll fix it).

> the power of artificial intelligence is not so great, the plugin compiles, but for some reason the execute command functions do not work

I'll release a new version with the updates later today (in a few hours probably).

**Comment by srnyx** [comment]
> if they leave instead of respawning, it will wait for them to rejoin

Wait, if someone leaves the server when they die (instead of clicking Respawn), when they rejoin, will they still be on the death screen, or will they automatically respawn?

**Comment by Dizover** [comment]
no, they will be on death screen even if the leave server

**Comment by Dizover** [comment]
even if server restarts, i tested it

**Comment by srnyx** [comment]
> no, they will be on death screen even if the leave server. So they anyway will press "Respawn"

Ok, that makes it a bit simpler then lmao, the restarting issue will still be there if the server restarts while they are on the death screen. Since I'm making it save the "dead players" in memory (which is reset when the server restarts).

**Comment by Dizover** [comment]
ah that's ok, server admins can do /gamerule doImmediateRespawn true so it's "solve" issue. and a bit of AI code, maybe this code better, still don't execute commands 
[limitedlives_modified_code.zip](https://github.com/srnyx/limited-lives/files/11336079/limitedlives_modified_code.zip)
[limited-lives-master3_compiled.zip](https://github.com/srnyx/limited-lives/files/11336082/limited-lives-master3_compiled.zip)

**Comment by srnyx** [comment]
>  and a bit of AI code, maybe this code better, still don't execute commands

It's fine, I already wrote all of the code for it (as well as even more features), thanks though

**Comment by srnyx** [comment]
Hi, so I'm also having issues with the commands executing so the update might take a little longer to update...

**Comment by Dizover** [comment]
If you have problems with the implementation of features, my programmer friend can help, he has experience of creating plugins

**Comment by Dizover** [comment]
IT'S WORKING, AI is a power 
[limited_lives_AI_rewriten.zip](https://github.com/srnyx/limited-lives/files/11341206/limited_lives_AI_rewriten.zip)

**Comment by Dizover** [comment]
In this version, I added settings depending on which the killer will take all lives, the last life, or will not take lives, in the zip file the modified code and compiled plugin [limited_lives3_AI_rewriten.zip](https://github.com/srnyx/limited-lives/files/11344055/limited_lives3_AI_rewriten.zip)

**Comment by srnyx** [comment]
> In this version, I added settings depending on which the killer will take all lives, the last life, or will not take lives, in the zip file the modified code and compiled plugin [limited_lives3_AI_rewriten.zip](https://github.com/srnyx/limited-lives/files/11344055/limited_lives3_AI_rewriten.zip)

I already added that (releasing in the next version), thanks though. *By the way, I probably won't be using any of the AI code, because it's always poorly written, it doesn't know how to use my API or how to match my style.*

**Comment by Dizover** [comment]
oh ok, but you can still look at that code and see if it's so badly written, and tell me if it is, it's interesting for me

**Comment by srnyx** [comment]
https://github.com/srnyx/limited-lives/commit/a1c3150409d4c45eb69f901c626d9d389401901e
