### ISSUE TITLE
Crafting recipe

### ISSUE THREAD

**Issue by Jer1o** [srnyx/limited-lives#3]
### What and How?

Make a crafting recipe that allows you to craft lives that can also be customizable by the config file

### Why?

So non-operators can get lives without usage of commands

### Are there alternatives?

Not sure

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by srnyx** [comment]
Working on this by the way. Making changes to [my API](https://api.srnyx.com) to make it easier to do, should be done soon!
