### ISSUE TITLE
Worldguard regions support

### ISSUE THREAD

**Issue by iRazvan2745** [srnyx/limited-lives#6]
Just block certain regions crom losing lives like warp pvp or event

**Comment by srnyx** [comment]
Started a bit: https://github.com/srnyx/limited-lives/commit/26de1ea9599806279767824e2b00e6e54263967b
*Download: https://github.com/srnyx/limited-lives/actions/runs/6269975973*

**Comment by srnyx** [comment]
https://github.com/srnyx/limited-lives/commit/26de1ea9599806279767824e2b00e6e54263967b
https://github.com/srnyx/limited-lives/commit/e529305980ff72a014611da56264a985371f722e
