### ISSUE TITLE
Commission

### ISSUE THREAD

**Issue by NoodleDood1e** [srnyx/limited-lives#7]
### What and How?

Hello, i'd like to _commission_ a few new features for the Limited Lives plugin, if thats possible
(Ordered them in terms of importance for me)

**1. The ability to give away lives to other players with a command**

> A command, maybe something like /givelife [Player]
> On use, the command will reduce the user's amount of lives by one, and it will add one live to the target.
> It should probably not let you give away your last life, so you cant kill yourself with it.

**2. Give players some time after they first join the server when the lives mechanic isnt active**

> After a player joins the server for the first time, there should be a timer.
> While this timer is still running, none of the player's deaths should reduce their amount of lives
> (Not necessary, but highly preferable) This timer should be unique to each person, and only tick down when they're online.

**3. Interraction with the keepinventory gamerule**

> If the server has the gamerule set to true, players should only drop items when they lose their last life, so the items in their inventory can be picked by other players.
> This should probably be a toggle in the config

**4. Diffirent max amounts of lives for diffirent players**

> An ability to set certain player's max life limit above or below the global limit

### Why?

Im currently working on the next season of my minecraft server, and these features would help me immensly! I'd be very thankful if you could add them, and im sure some other players would find these additions handy.

### Are there alternatives?

Im okay with my ideas being stripped down, simplified, or outright not implemented, if they are not possible for any reason!

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

**By "commission", i do mean that i'm going to pay for these features!** Hope im not asking for too much.
If you are interested, please, contact me via Discord. There we can discuss the price & the ideas being implemented or not. And if you are not interested, please do tell me as well, so i will not disturb you any further!

My discord: @noodledoodle

Thank you for your time!

**Comment by srnyx** [comment]
**Split into 4 separate issues:**
1. #8 
2. #9 
3. #10 
4. #11
